### ISSUE TITLE
sudo tourbillon run failed

### ISSUE THREAD

**Issue by juan-pe** [tourbillonpy/tourbillon-agent#3]
command not found output trying to run tourbillon
juan-pe@bowie:~$ sudo tourbillon run
sudo: tourbillon: command not found

info about system:
$> uname -a
Linux bowie 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$>echo ${DISTRIB_ID}}
Ubuntu
$> echo ${DISTRIB_RELEASE}}
14.04

**Comment by ffaraone** [comment]
Try:

`sudo -i tourbillon run`

**Comment by juan-pe** [comment]
worked!
